<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpecFlow" Version="4.13.0" />
    <PackageReference Include="SpecFlow.XUnit" Version="3.9.77" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="4.13.0" PrivateAssets="all" />
    <PackageReference Include="xunit" Version="2.5.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPCalculator\BPCalculator.csproj" />
  </ItemGroup>

</Project>