name: Bp_Application_Build

on:
  push:
    branches:
     # - main
      - dev
     # - test
     # - stage

jobs:
  BP-application-deployment:

    runs-on: self-hosted
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: actions/setup-dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'

        - name: Release Build
          run: dotnet build --configuration Release