name: Bp_Application_Build

on:
  push:
    branches:
     # - main
    - dev
     # - test
     # - stage

jobs:
  BP-application-deployment:

    runs-on: WIN-Q0GEAOGCQB5
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
