name: Bp_Application_Build_and_Deployment_CA1

on:
  workflow_dispatch:
  push:
    branches:
     # - main
      - dev
      - qa
    paths-ignore:
      - '.github/workflows/**'

env:
  BRANCH: ${{ github.ref_name }}
#  PUBLISH_PROFILE_DEV: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
#  PUBLISH_PROFILE_QA: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
  REGISTRY_IMAGE: bpcalculator
  DEV_ENV: dev-nonprod01
  QA_ENV: qa-nonprod01

jobs:
  BP-application-CI:
    runs-on: windows-2022

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: actions/setup-dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'
        
        - name: Install Sonar Scanner
          run: |
            dotnet tool install --global dotnet-sonarscanner
            dotnet tool install --global dotnet-coverage

        - name: Sonar Scanner Begin Analysis
          run: |
            dotnet sonarscanner begin `
              /o:"ca1" `
              /k:"BPCalculatorCA1" `
              /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml `
              /d:sonar.token=${{ secrets.SONAR_TOKEN }}

        - name: Release Build
          run: dotnet build --configuration Release --no-incremental

        - name: Run unit tests
          run: dotnet test BPCalculator.sln --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutput=coverage.xml /p:CoverletOutputFormat=opencover --collect "Code coverage"
        
        - name: Sonar Scanner End Analysis
          run: |
            dotnet sonarscanner end `
              /d:sonar.login=${{ secrets.SONAR_TOKEN }}

        
          
            
        # - name: Sonar Scan
        #   uses: sonarsource/sonarqube-scan-action@master
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #   with:
        #     projectBaseDir: 'BPCalculator'  #Scans only BPCalculator folder to reduce the lines of code from sonarcloud since we are using free version
        #     args: >
        #       -Dsonar.projectKey=CA1_bloodpressurecalculator
        #       -Dsonar.verbose=true
        #       -Dsonar.sourceEncoding=UTF-8
        #       -Dsonar.organization=ca1
        #       -Dsonar.projectVersion=1.0
        #       -Dsonar.host.url=https://sonarcloud.io
        #       -Dsonar.branches=$BRANCH 

        # - name: Sourcing Variables for Branch Tagging
        #   id: Sourcing-Variables
        #   run: |
        #     BRANCH=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3

        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3

        # - name: Cache Docker layers
        #   if: true
        #   uses: actions/cache@v3
        #   with:
        #     path: /tmp/.buildx-cache
        #     key: ${{ runner.os }}-buildx-${{ github.sha }}
        #     restore-keys: |
        #       ${{ runner.os }}-buildx-

        # - name: Docker Login to Azure Container Registry
        #   uses: docker/login-action@v3.0.0
        #   with:
        #     registry: tudublinca.azurecr.io
        #     username: tudublinca  # Logging through service account.
        #     password: ${{ secrets.AZURE_DOCKER_PASSWORD }}

        # - name: Build Docker image
        #   uses: docker/build-push-action@v5
        #   with:
        #     context: .
        #   #  push: true
        #     platforms: linux/amd64,linux/arm64
        #     cache-from: type=local,src=/tmp/.buildx-cache
        #     cache-to: type=local,dest=/tmp/.buildx-cache
        #     file: ./Dockerfile
        #     tags: tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }}

        
        # - name: Docker Image Build and Push
        #   run: |
        #     docker build -t tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }} .
        #     docker push tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }}
        #     docker images


        # - name: Run Trivy vulnerability scanner
        #   uses: aquasecurity/trivy-action@0.28.0
        #   with:
        #     image-ref: 'tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }}'
        #     format: 'table'
        #   #  exit-code: '1'
        #     ignore-unfixed: true
        #     vuln-type: 'os,library'
        #     severity: 'CRITICAL,HIGH,MEDIUM,LOW'
        

  # BP-application-CD-dev-Non-Production:
  #   if: ${{ always() && github.ref == 'refs/heads/dev' }}
  #   needs: BP-application-CI
  #   runs-on: ubuntu-22.04  
    
  #   steps:
  #   - name: Deploy to Azure Web App for Container for dev environment
  #     uses: azure/webapps-deploy@v3
  #     with:
  #       app-name: ${{ env.DEV_ENV }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
  #       images: tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }}

  # BP-application-CD-QA-Non-Production:
  #   if: ${{ always() && github.ref == 'refs/heads/qa' }}
  #   needs: BP-application-CI
  #   runs-on: ubuntu-22.04  
    
  #   steps:
  #   - name: Deploy to Azure Web App for Container for Qa Environment
  #     uses: azure/webapps-deploy@v3
  #     with:
  #       app-name: ${{ env.QA_ENV }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
  #       images: tudublinca.azurecr.io/tudublin/bpcalculator:${{ github.run_number }}

  # BP-application-CD-Production:
  #   if: ${{ always() && github.ref == 'refs/heads/main' }}
  #   environment: 'prod'
  #   needs: BP-application-CI
  #   runs-on: ubuntu-22.04

  #   steps:
  #   - name: Populating variables For Non Production Environments
  #     env:
  #       BRANCH: ${{ github.ref_name }}
  #     run: |
  #       if [ "$BRANCH" = "main" ]; then
  #         WEBAPP="${{ env.PROD_ENV }}"
  #       elif [ "$BRANCH" = "stage" ]; then
  #         WEBAPP="${{ env.STAGE_ENV }}"
  #       fi

  # Post-Deployment-Tests:
  #   if: ${{ always() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test') }}
  #   # needs: 
  #   # #  - BP-application-CD-dev-Non-Production
  #   #   - BP-application-CD-QA-Non-Production
  #   runs-on: ubuntu-22.04

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Pull Docker image for ZAP
  #     run: docker pull zaproxy/zap-weekly
    
  #   - name: Pull Docker image for k6
  #     run: docker pull grafana/k6
      
  #   - name: Run baseline scan on dev environment
  #     if: github.ref == 'refs/heads/dev'
  #     run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t https://dev-nonprod01.azurewebsites.net/ -I -r zapreport.html

  #   - name: Run baseline scan test on qa environment
  #     if: github.ref == 'refs/heads/qa'
  #     run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t https://qa-nonprod01.azurewebsites.net/ -I -r zapreport.html
    

  #   - name: Run k6 load test, capture report
  #     if: github.ref == 'refs/heads/dev'
  #     run: docker run -i grafana/k6 run - <k6/perf-dev.js > k6report.txt

  #   - name: Run k6 load test, capture report
  #     if: github.ref == 'refs/heads/qa'
  #     run: docker run -i grafana/k6 run - <k6/perf-qa.js > k6report.txt
 
  #   - name: Upload Reports
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: ZAP Report
  #       path: /report/zapreport.html

  #   - name: Upload Reports
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: K6 Report
  #       path: ${{ github.workspace }}/k6report.txt